import type { CatalogAsset } from "./types";

export const CATALOG_VERSION = "2026-10-06.v2";
// Manual curation, not a live availability feed. Legacy chains remain demo targets.
// Regional metadata describes the underlying exposure, not investor eligibility.
export const ASSET_CATALOG: readonly CatalogAsset[] = [
  {
    id: "ondo-nvda",
    ticker: "NVDAon",
    displayTicker: "NVDAon",
    name: "NVIDIA (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "compute", "semiconductors", "data-centers"],
    exposures: ["accelerated-compute", "semiconductor-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to NVIDIA. Not direct ownership of the underlying security.",
    underlying: "NVDA",
    providerUrl: "https://app.ondo.finance/assets/NVDAon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 172.4,
  },
  {
    id: "ondo-amd",
    ticker: "AMDon",
    displayTicker: "AMDon",
    name: "Advanced Micro Devices (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "compute", "semiconductors", "data-centers"],
    exposures: ["accelerated-compute", "semiconductor-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Advanced Micro Devices. Not direct ownership of the underlying security.",
    underlying: "AMD",
    providerUrl: "https://app.ondo.finance/assets/AMDon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 204.1,
  },
  {
    id: "ondo-avgo",
    ticker: "AVGOon",
    displayTicker: "AVGOon",
    name: "Broadcom (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "semiconductors", "networking", "data-centers"],
    exposures: ["semiconductor-demand", "data-center-networking"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Broadcom. Not direct ownership of the underlying security.",
    underlying: "AVGO",
    providerUrl: "https://app.ondo.finance/assets/AVGOon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-tsm",
    ticker: "TSMon",
    displayTicker: "TSMon",
    name: "Taiwan Semiconductor Manufacturing ADR (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "global",
    countryExposure: ["TW"],
    currencyExposure: ["TWD", "USD"],
    marketExposure: ["semiconductors"],
    availabilityScope: "demo",
    themes: ["ai", "semiconductors", "manufacturing"],
    exposures: ["semiconductor-demand", "chip-manufacturing"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Taiwan Semiconductor Manufacturing ADR. Not direct ownership of the underlying security.",
    underlying: "TSM",
    providerUrl: "https://app.ondo.finance/assets/TSMon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-msft",
    ticker: "MSFTon",
    displayTicker: "MSFTon",
    name: "Microsoft (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "big-tech", "cloud", "software", "compute"],
    exposures: ["cloud-computing", "enterprise-software"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Microsoft. Not direct ownership of the underlying security.",
    underlying: "MSFT",
    providerUrl: "https://app.ondo.finance/assets/MSFTon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-aapl",
    ticker: "AAPLon",
    displayTicker: "AAPLon",
    name: "Apple (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["big-tech", "consumer-technology"],
    exposures: ["consumer-devices", "technology-adoption"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Apple. Not direct ownership of the underlying security.",
    underlying: "AAPL",
    providerUrl: "https://app.ondo.finance/assets/AAPLon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-googl",
    ticker: "GOOGLon",
    displayTicker: "GOOGLon",
    name: "Alphabet (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "big-tech", "cloud", "compute"],
    exposures: ["cloud-computing", "digital-advertising"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Alphabet. Not direct ownership of the underlying security.",
    underlying: "GOOGL",
    providerUrl: "https://app.ondo.finance/assets/GOOGLon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-amzn",
    ticker: "AMZNon",
    displayTicker: "AMZNon",
    name: "Amazon (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "big-tech", "cloud", "compute"],
    exposures: ["cloud-computing", "digital-commerce"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Amazon. Not direct ownership of the underlying security.",
    underlying: "AMZN",
    providerUrl: "https://app.ondo.finance/assets/AMZNon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-meta",
    ticker: "METAon",
    displayTicker: "METAon",
    name: "Meta Platforms (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "big-tech", "software"],
    exposures: ["digital-advertising", "technology-adoption"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Meta Platforms. Not direct ownership of the underlying security.",
    underlying: "META",
    providerUrl: "https://app.ondo.finance/assets/METAon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-vrt",
    ticker: "VRTon",
    displayTicker: "VRTon",
    name: "Vertiv (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["ai", "data-centers", "infrastructure", "electricity"],
    exposures: ["data-center-power", "data-center-cooling"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Vertiv. Not direct ownership of the underlying security.",
    underlying: "VRT",
    providerUrl: "https://app.ondo.finance/assets/VRTon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-nee",
    ticker: "NEEon",
    displayTicker: "NEEon",
    name: "NextEra Energy (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["energy", "electricity", "infrastructure"],
    exposures: ["power-generation", "electricity-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to NextEra Energy. Not direct ownership of the underlying security.",
    underlying: "NEE",
    providerUrl: "https://app.ondo.finance/assets/NEEon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-ceg",
    ticker: "CEGon",
    displayTicker: "CEGon",
    name: "Constellation Energy (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["energy", "electricity", "infrastructure", "nuclear"],
    exposures: ["power-generation", "electricity-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Constellation Energy. Not direct ownership of the underlying security.",
    underlying: "CEG",
    providerUrl: "https://app.ondo.finance/assets/CEGon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-xom",
    ticker: "XOMon",
    displayTicker: "XOMon",
    name: "Exxon Mobil (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["energy", "commodities"],
    exposures: ["oil-and-gas", "energy-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Exxon Mobil. Not direct ownership of the underlying security.",
    underlying: "XOM",
    providerUrl: "https://app.ondo.finance/assets/XOMon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-v",
    ticker: "Von",
    displayTicker: "Von",
    name: "Visa (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["payments", "financial-infrastructure"],
    exposures: ["payment-networks", "digital-payments"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Visa. Not direct ownership of the underlying security.",
    underlying: "V",
    providerUrl: "https://app.ondo.finance/assets/Von",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-ma",
    ticker: "MAon",
    displayTicker: "MAon",
    name: "Mastercard (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["payments", "financial-infrastructure"],
    exposures: ["payment-networks", "digital-payments"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Mastercard. Not direct ownership of the underlying security.",
    underlying: "MA",
    providerUrl: "https://app.ondo.finance/assets/MAon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-pypl",
    ticker: "PYPLon",
    displayTicker: "PYPLon",
    name: "PayPal (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["payments", "stablecoins"],
    exposures: ["digital-payments", "stablecoin-infrastructure"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to PayPal. Not direct ownership of the underlying security.",
    underlying: "PYPL",
    providerUrl: "https://app.ondo.finance/assets/PYPLon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-crcl",
    ticker: "CRCLon",
    displayTicker: "CRCLon",
    name: "Circle Internet Group (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["payments", "stablecoins", "tokenization", "rwa"],
    exposures: ["stablecoin-infrastructure", "digital-payments"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "concentration-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Circle Internet Group. Not direct ownership of the underlying security.",
    underlying: "CRCL",
    providerUrl: "https://app.ondo.finance/assets/CRCLon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-spy",
    ticker: "SPYon",
    displayTicker: "SPYon",
    name: "SPDR S&P 500 ETF Trust (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["broad-market", "us-equity"],
    exposures: ["broad-us-equity"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to SPDR S&P 500 ETF Trust. Not direct ownership of the underlying security.",
    underlying: "SPY",
    providerUrl: "https://app.ondo.finance/assets/SPYon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-qqq",
    ticker: "QQQon",
    displayTicker: "QQQon",
    name: "Invesco QQQ Trust (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["technology", "nasdaq", "big-tech", "ai"],
    exposures: ["nasdaq-equity", "technology-adoption"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Invesco QQQ Trust. Not direct ownership of the underlying security.",
    underlying: "QQQ",
    providerUrl: "https://app.ondo.finance/assets/QQQon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-smh",
    ticker: "SMHon",
    displayTicker: "SMHon",
    name: "VanEck Semiconductor ETF (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "global",
    countryExposure: [],
    currencyExposure: ["USD"],
    marketExposure: ["semiconductors"],
    availabilityScope: "demo",
    themes: ["semiconductors", "ai", "compute"],
    exposures: ["semiconductor-demand", "chip-manufacturing"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to VanEck Semiconductor ETF. Not direct ownership of the underlying security.",
    underlying: "SMH",
    providerUrl: "https://app.ondo.finance/assets/SMHon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-xlu",
    ticker: "XLUon",
    displayTicker: "XLUon",
    name: "Utilities Select Sector SPDR Fund (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["utilities", "energy", "electricity", "infrastructure"],
    exposures: ["power-generation", "electricity-demand"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Utilities Select Sector SPDR Fund. Not direct ownership of the underlying security.",
    underlying: "XLU",
    providerUrl: "https://app.ondo.finance/assets/XLUon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-xle",
    ticker: "XLEon",
    displayTicker: "XLEon",
    name: "Energy Select Sector SPDR Fund (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-equities"],
    availabilityScope: "demo",
    themes: ["energy", "commodities"],
    exposures: ["energy-demand", "oil-and-gas"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to Energy Select Sector SPDR Fund. Not direct ownership of the underlying security.",
    underlying: "XLE",
    providerUrl: "https://app.ondo.finance/assets/XLEon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-gld",
    ticker: "GLDon",
    displayTicker: "GLDon",
    name: "SPDR Gold Shares (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "global",
    countryExposure: [],
    currencyExposure: ["USD"],
    marketExposure: ["gold"],
    availabilityScope: "demo",
    themes: ["gold", "commodities", "monetary-instability"],
    exposures: ["gold-price", "monetary-hedge"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to SPDR Gold Shares. Not direct ownership of the underlying security.",
    underlying: "GLD",
    providerUrl: "https://app.ondo.finance/assets/GLDon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-tlt",
    ticker: "TLTon",
    displayTicker: "TLTon",
    name: "iShares 20+ Year Treasury Bond ETF (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-treasuries"],
    availabilityScope: "demo",
    themes: ["treasuries", "fixed-income"],
    exposures: ["long-duration-treasuries", "interest-rate-duration"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to iShares 20+ Year Treasury Bond ETF. Not direct ownership of the underlying security.",
    underlying: "TLT",
    providerUrl: "https://app.ondo.finance/assets/TLTon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "ondo-sgov",
    ticker: "SGOVon",
    displayTicker: "SGOVon",
    name: "iShares 0-3 Month Treasury Bond ETF (Ondo tokenized)",
    instrumentType: "tokenized_etf",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-treasuries"],
    availabilityScope: "demo",
    themes: ["treasuries", "fixed-income", "liquidity"],
    exposures: ["short-duration-treasuries", "usd-liquidity"],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "eligibility-restrictions",
      "fund-risk",
    ],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized economic exposure to iShares 0-3 Month Treasury Bond ETF. Not direct ownership of the underlying security.",
    underlying: "SGOV",
    providerUrl: "https://app.ondo.finance/assets/SGOVon",
    notes:
      "Manually curated demo representation targeting Solana. Per-instrument chain deployment, eligibility and tradability require verification before any real integration. No live availability is asserted.",
    demoPrice: 100,
  },
  {
    id: "sol",
    ticker: "SOL",
    displayTicker: "SOL",
    name: "Solana",
    instrumentType: "digital_asset",
    provider: "solana",
    chain: "solana",
    region: "global",
    countryExposure: [],
    currencyExposure: [],
    marketExposure: ["blockchain-settlement"],
    availabilityScope: "demo",
    themes: ["solana", "blockchain", "infrastructure", "tokenization", "rwa", "payments"],
    exposures: ["blockchain-settlement", "solana-ecosystem", "tokenization-infrastructure"],
    riskTags: ["volatility", "protocol-risk", "regulatory-risk"],
    executionStatus: "demo-only",
    enabled: true,
    description: "Native network asset. Network adoption does not guarantee token returns.",
    providerUrl: "https://solana.com/learn/introduction-to-solana-tokens",
    notes:
      "Curated for simulation only. No current price, return, eligibility or trading availability supplied.",
    demoPrice: 158.2,
  },
  {
    id: "usdc",
    ticker: "USDC",
    displayTicker: "USDC",
    name: "USDC",
    instrumentType: "stablecoin",
    provider: "circle",
    chain: "solana",
    region: "global",
    countryExposure: [],
    currencyExposure: ["USD"],
    marketExposure: ["usd-liquidity"],
    availabilityScope: "demo",
    themes: ["stablecoins", "payments", "liquidity", "tokenization", "rwa"],
    exposures: ["usd-liquidity", "digital-payments", "stablecoin-infrastructure"],
    riskTags: ["issuer-risk", "depeg-risk", "regulatory-risk"],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "USD stablecoin; holding it does not grant equity ownership or participation in issuer revenue.",
    providerUrl: "https://www.circle.com/multi-chain-usdc/solana",
    notes:
      "Curated for simulation only. No current price, return, eligibility or trading availability supplied.",
    demoPrice: 1,
  },
  {
    id: "pyusd",
    ticker: "PYUSD",
    displayTicker: "PYUSD",
    name: "PayPal USD",
    instrumentType: "stablecoin",
    provider: "paxos",
    chain: "solana",
    region: "global",
    countryExposure: [],
    currencyExposure: ["USD"],
    marketExposure: ["usd-liquidity"],
    availabilityScope: "demo",
    themes: ["stablecoins", "payments", "liquidity"],
    exposures: ["usd-liquidity", "digital-payments", "stablecoin-infrastructure"],
    riskTags: ["issuer-risk", "depeg-risk", "regulatory-risk"],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "USD stablecoin issued by Paxos, branded PayPal. Not equity or a claim on payment growth.",
    providerUrl: "https://developer.paypal.com/community/blog/pyusd-solana-token-extensions/",
    notes:
      "Curated for simulation only. No current price, return, eligibility or trading availability supplied.",
    demoPrice: 1,
  },
  {
    id: "usdy",
    ticker: "USDY",
    displayTicker: "USDY",
    name: "Ondo US Dollar Yield",
    instrumentType: "tokenized_fixed_income",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-treasuries"],
    availabilityScope: "demo",
    themes: ["treasuries", "fixed-income", "tokenization", "rwa"],
    exposures: ["short-duration-treasuries", "tokenized-treasuries"],
    riskTags: ["issuer-risk", "interest-rate-risk", "eligibility-restrictions"],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized instrument with short-term US Treasury and bank-deposit exposure. Not Ondo equity or direct participation in tokenization platform revenue.",
    providerUrl: "https://ondo.finance/usdy",
    notes:
      "Curated for simulation only. No current price, return, eligibility or trading availability supplied.",
    demoPrice: 100,
  },
  {
    id: "ousg",
    ticker: "OUSG",
    displayTicker: "OUSG",
    name: "Ondo Short-Term US Government Treasuries",
    instrumentType: "tokenized_fixed_income",
    provider: "ondo",
    chain: "solana",
    region: "us",
    countryExposure: ["US"],
    currencyExposure: ["USD"],
    marketExposure: ["us-treasuries"],
    availabilityScope: "demo",
    themes: ["treasuries", "fixed-income", "tokenization", "rwa"],
    exposures: ["short-duration-treasuries", "tokenized-treasuries"],
    riskTags: ["fund-risk", "issuer-risk", "eligibility-restrictions"],
    executionStatus: "demo-only",
    enabled: true,
    description:
      "Tokenized fund exposure to short-term US government securities. Not equity in the tokenization provider.",
    providerUrl: "https://ondo.finance/ousg",
    notes:
      "Curated for simulation only. No current price, return, eligibility or trading availability supplied.",
    demoPrice: 100,
  },
  // New entries reuse the v1 nominal demo-price fixture (100); never a market quote.
  {
    chain: "solana",
    executionStatus: "demo-only",
    availabilityScope: "provider-specific",
    enabled: true,
    demoPrice: 100,
    id: "ondo-pbr",
    ticker: "PBRon",
    displayTicker: "PBRon",
    name: "Petrobras (Ondo tokenized)",
    instrumentType: "tokenized_equity",
    provider: "ondo",
    themes: ["brazil", "energy", "oil-and-gas", "commodities", "emerging-markets"],
    exposures: [
      "brazil-equities",
      "brazil-energy",
      "oil-and-gas",
      "commodity-exporters",
      "emerging-market-equities",
    ],
    riskTags: [
      "market-risk",
      "issuer-risk",
      "tracking-risk",
      "country-risk",
      "currency-risk",
      "commodity-risk",
      "concentration-risk",
      "eligibility-restrictions",
    ],
    description:
      "Tokenized economic exposure to Petróleo Brasileiro S.A. – Petrobras through the U.S.-listed PBR instrument. It provides economic exposure to the underlying security and does not grant direct ownership of Petrobras shares.",
    underlying: "PBR",
    region: "brazil",
    countryExposure: ["BR"],
    currencyExposure: ["BRL", "USD"],
    marketExposure: ["brazil-equities", "brazil-energy", "oil-and-gas"],
    providerUrl: "https://app.ondo.finance/assets/PBRon",
    notes:
      "Verified as an Ondo tokenized security with native Solana availability. Eligibility, jurisdiction, liquidity and trading conditions remain provider-specific. No live availability or return is asserted by VicTy.",
  },
  {
    chain: "solana",
    executionStatus: "demo-only",
    availabilityScope: "provider-specific",
    enabled: true,
    demoPrice: 100,
    id: "backpack-ewz",
    ticker: "EWZ",
    displayTicker: "EWZ",
    name: "iShares MSCI Brazil ETF (Backpack tokenized)",
    instrumentType: "tokenized_etf",
    provider: "backpack",
    themes: ["brazil", "latam", "emerging-markets", "equities"],
    exposures: ["brazil-equities", "brazil-large-mid-cap", "emerging-market-equities"],
    riskTags: [
      "market-risk",
      "country-risk",
      "currency-risk",
      "issuer-risk",
      "tracking-risk",
      "concentration-risk",
    ],
    description:
      "Tokenized representation of the iShares MSCI Brazil ETF, providing broad exposure to large- and mid-cap Brazilian equities.",
    underlying: "EWZ",
    region: "brazil",
    countryExposure: ["BR"],
    currencyExposure: ["BRL", "USD"],
    marketExposure: ["brazil-equities"],
    providerUrl: "https://learn.backpack.exchange/blog/tokenized-ishares-msci-brazil-etf-ewz",
    notes:
      "Verified as tokenized on Solana through Backpack Securities. Provider-specific eligibility, redemption and trading conditions apply. VicTy does not assert live availability.",
  },
  {
    chain: "solana",
    executionStatus: "demo-only",
    availabilityScope: "provider-specific",
    enabled: true,
    demoPrice: 100,
    id: "etherfuse-tesouro",
    ticker: "TESOURO",
    displayTicker: "TESOURO",
    name: "Etherfuse Brazilian Treasury Bonds",
    instrumentType: "tokenized_fixed_income",
    provider: "etherfuse",
    themes: ["brazil", "treasuries", "fixed-income", "sovereign-debt", "rwa", "tokenization"],
    exposures: [
      "brazil-sovereign-debt",
      "brazil-interest-rates",
      "brazil-local-fixed-income",
      "brl-fixed-income",
      "tokenized-treasuries",
    ],
    riskTags: [
      "sovereign-risk",
      "interest-rate-risk",
      "currency-risk",
      "issuer-risk",
      "liquidity-risk",
      "regulatory-risk",
    ],
    description:
      "Tokenized exposure to Brazilian federal treasury bonds through Etherfuse Stablebonds, denominated in Brazilian reais.",
    region: "brazil",
    countryExposure: ["BR"],
    currencyExposure: ["BRL"],
    marketExposure: ["brazil-fixed-income", "brazil-sovereign-debt", "brazil-interest-rates"],
    providerUrl: "https://etherfuse.com/markets/brazil",
    notes:
      "TESOURO is available on Solana. Do not hard-code current APY, price or maturity because these are live values that change. Eligibility and liquidity remain provider-specific.",
  },
  {
    chain: "solana",
    executionStatus: "demo-only",
    availabilityScope: "provider-specific",
    enabled: true,
    demoPrice: 100,
    id: "transfero-brz",
    ticker: "BRZ",
    displayTicker: "BRZ",
    name: "BRZ",
    instrumentType: "stablecoin",
    provider: "transfero",
    themes: ["brazil", "stablecoins", "payments", "brl", "liquidity", "cross-border"],
    exposures: ["brl-liquidity", "brazilian-real", "digital-payments", "cross-border-settlement"],
    riskTags: ["issuer-risk", "depeg-risk", "reserve-risk", "regulatory-risk", "currency-risk"],
    description:
      "Brazilian-real stablecoin designed to maintain a 1:1 reference to BRL. It represents BRL-denominated liquidity, not equity exposure to the Brazilian economy.",
    region: "brazil",
    countryExposure: ["BR"],
    currencyExposure: ["BRL"],
    marketExposure: ["brl-liquidity", "digital-payments"],
    providerUrl: "https://transfero.com/brz-stablecoin",
    notes:
      "Transfero lists an official BRZ deployment on Solana. BRZ should not be treated as a growth asset or as equity exposure to Brazil.",
  },
  {
    chain: "solana",
    executionStatus: "demo-only",
    availabilityScope: "provider-specific",
    enabled: true,
    demoPrice: 100,
    id: "etherfuse-cetes",
    ticker: "CETES",
    displayTicker: "CETES",
    name: "Etherfuse Mexican Treasury Certificates",
    instrumentType: "tokenized_fixed_income",
    provider: "etherfuse",
    themes: [
      "mexico",
      "latam",
      "treasuries",
      "fixed-income",
      "sovereign-debt",
      "rwa",
      "tokenization",
    ],
    exposures: [
      "mexico-sovereign-debt",
      "mexico-interest-rates",
      "mexico-local-fixed-income",
      "mxn-fixed-income",
      "tokenized-treasuries",
    ],
    riskTags: [
      "sovereign-risk",
      "interest-rate-risk",
      "currency-risk",
      "issuer-risk",
      "liquidity-risk",
      "regulatory-risk",
    ],
    description:
      "Tokenized exposure to Mexican federal treasury certificates through Etherfuse Stablebonds, denominated in Mexican pesos.",
    region: "latam",
    countryExposure: ["MX"],
    currencyExposure: ["MXN"],
    marketExposure: ["mexico-fixed-income", "mexico-sovereign-debt", "mexico-interest-rates"],
    providerUrl: "https://etherfuse.com/markets/mexico",
    notes:
      "CETES is available on Solana. Do not hard-code current yield, price or maturity. Eligibility and liquidity remain provider-specific.",
  },
];
