import type { Instrument } from './instruments.js';

// Curated from the victylp demo catalog (2026-10-06.v2). Matching metadata (themes, exposures,
// region, risk tags) came from there; prices did not: they come from Jupiter.
//
// Only USDC is approved: its mint is confirmed. Everything else is 'unavailable' until spike S1
// confirms its mint, decimals and token program, someone reviews the evidence, and buy and sell
// are checked for the planned amounts (PRD §10.3). Approving one means filling mint, decimals and
// evidence and changing its status here; test/catalog.test.ts refuses an approval without them.
export const registry: readonly Instrument[] = [
  {
    id: 'ins_ondo_nvda',
    symbol: 'NVDAon',
    name: 'NVIDIA (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Accelerated compute',
    issuerName: 'Ondo Finance',
    underlying: 'NVDA',
    represents: 'Tokenized economic exposure to NVIDIA. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'compute', 'semiconductors', 'data-centers'],
    exposures: ['accelerated-compute', 'semiconductor-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/NVDAon',
    evidence: [],
  },
  {
    id: 'ins_ondo_amd',
    symbol: 'AMDon',
    name: 'Advanced Micro Devices (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Accelerated compute',
    issuerName: 'Ondo Finance',
    underlying: 'AMD',
    represents: 'Tokenized economic exposure to Advanced Micro Devices. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'compute', 'semiconductors', 'data-centers'],
    exposures: ['accelerated-compute', 'semiconductor-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/AMDon',
    evidence: [],
  },
  {
    id: 'ins_ondo_avgo',
    symbol: 'AVGOon',
    name: 'Broadcom (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Semiconductor demand',
    issuerName: 'Ondo Finance',
    underlying: 'AVGO',
    represents: 'Tokenized economic exposure to Broadcom. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'semiconductors', 'networking', 'data-centers'],
    exposures: ['semiconductor-demand', 'data-center-networking'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/AVGOon',
    evidence: [],
  },
  {
    id: 'ins_ondo_tsm',
    symbol: 'TSMon',
    name: 'Taiwan Semiconductor Manufacturing ADR (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Semiconductor demand',
    issuerName: 'Ondo Finance',
    underlying: 'TSM',
    represents: 'Tokenized economic exposure to Taiwan Semiconductor Manufacturing ADR. Not direct ownership of the underlying security.',
    region: 'global',
    countryExposure: ['TW'],
    currencyExposure: ['TWD', 'USD'],
    themes: ['ai', 'semiconductors', 'manufacturing'],
    exposures: ['semiconductor-demand', 'chip-manufacturing'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/TSMon',
    evidence: [],
  },
  {
    id: 'ins_ondo_msft',
    symbol: 'MSFTon',
    name: 'Microsoft (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Cloud computing',
    issuerName: 'Ondo Finance',
    underlying: 'MSFT',
    represents: 'Tokenized economic exposure to Microsoft. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'big-tech', 'cloud', 'software', 'compute'],
    exposures: ['cloud-computing', 'enterprise-software'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/MSFTon',
    evidence: [],
  },
  {
    id: 'ins_ondo_aapl',
    symbol: 'AAPLon',
    name: 'Apple (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Consumer devices',
    issuerName: 'Ondo Finance',
    underlying: 'AAPL',
    represents: 'Tokenized economic exposure to Apple. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['big-tech', 'consumer-technology'],
    exposures: ['consumer-devices', 'technology-adoption'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/AAPLon',
    evidence: [],
  },
  {
    id: 'ins_ondo_googl',
    symbol: 'GOOGLon',
    name: 'Alphabet (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Cloud computing',
    issuerName: 'Ondo Finance',
    underlying: 'GOOGL',
    represents: 'Tokenized economic exposure to Alphabet. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'big-tech', 'cloud', 'compute'],
    exposures: ['cloud-computing', 'digital-advertising'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/GOOGLon',
    evidence: [],
  },
  {
    id: 'ins_ondo_amzn',
    symbol: 'AMZNon',
    name: 'Amazon (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Cloud computing',
    issuerName: 'Ondo Finance',
    underlying: 'AMZN',
    represents: 'Tokenized economic exposure to Amazon. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'big-tech', 'cloud', 'compute'],
    exposures: ['cloud-computing', 'digital-commerce'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/AMZNon',
    evidence: [],
  },
  {
    id: 'ins_ondo_meta',
    symbol: 'METAon',
    name: 'Meta Platforms (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Digital advertising',
    issuerName: 'Ondo Finance',
    underlying: 'META',
    represents: 'Tokenized economic exposure to Meta Platforms. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'big-tech', 'software'],
    exposures: ['digital-advertising', 'technology-adoption'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/METAon',
    evidence: [],
  },
  {
    id: 'ins_ondo_vrt',
    symbol: 'VRTon',
    name: 'Vertiv (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Data center power',
    issuerName: 'Ondo Finance',
    underlying: 'VRT',
    represents: 'Tokenized economic exposure to Vertiv. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['ai', 'data-centers', 'infrastructure', 'electricity'],
    exposures: ['data-center-power', 'data-center-cooling'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/VRTon',
    evidence: [],
  },
  {
    id: 'ins_ondo_nee',
    symbol: 'NEEon',
    name: 'NextEra Energy (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Power generation',
    issuerName: 'Ondo Finance',
    underlying: 'NEE',
    represents: 'Tokenized economic exposure to NextEra Energy. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['energy', 'electricity', 'infrastructure'],
    exposures: ['power-generation', 'electricity-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/NEEon',
    evidence: [],
  },
  {
    id: 'ins_ondo_ceg',
    symbol: 'CEGon',
    name: 'Constellation Energy (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Power generation',
    issuerName: 'Ondo Finance',
    underlying: 'CEG',
    represents: 'Tokenized economic exposure to Constellation Energy. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['energy', 'electricity', 'infrastructure', 'nuclear'],
    exposures: ['power-generation', 'electricity-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/CEGon',
    evidence: [],
  },
  {
    id: 'ins_ondo_xom',
    symbol: 'XOMon',
    name: 'Exxon Mobil (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Oil and gas',
    issuerName: 'Ondo Finance',
    underlying: 'XOM',
    represents: 'Tokenized economic exposure to Exxon Mobil. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['energy', 'commodities'],
    exposures: ['oil-and-gas', 'energy-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/XOMon',
    evidence: [],
  },
  {
    id: 'ins_ondo_v',
    symbol: 'Von',
    name: 'Visa (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Payment networks',
    issuerName: 'Ondo Finance',
    underlying: 'V',
    represents: 'Tokenized economic exposure to Visa. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['payments', 'financial-infrastructure'],
    exposures: ['payment-networks', 'digital-payments'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/Von',
    evidence: [],
  },
  {
    id: 'ins_ondo_ma',
    symbol: 'MAon',
    name: 'Mastercard (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Payment networks',
    issuerName: 'Ondo Finance',
    underlying: 'MA',
    represents: 'Tokenized economic exposure to Mastercard. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['payments', 'financial-infrastructure'],
    exposures: ['payment-networks', 'digital-payments'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/MAon',
    evidence: [],
  },
  {
    id: 'ins_ondo_pypl',
    symbol: 'PYPLon',
    name: 'PayPal (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Digital payments',
    issuerName: 'Ondo Finance',
    underlying: 'PYPL',
    represents: 'Tokenized economic exposure to PayPal. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['payments', 'stablecoins'],
    exposures: ['digital-payments', 'stablecoin-infrastructure'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/PYPLon',
    evidence: [],
  },
  {
    id: 'ins_ondo_crcl',
    symbol: 'CRCLon',
    name: 'Circle Internet Group (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Stablecoin infrastructure',
    issuerName: 'Ondo Finance',
    underlying: 'CRCL',
    represents: 'Tokenized economic exposure to Circle Internet Group. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['payments', 'stablecoins', 'tokenization', 'rwa'],
    exposures: ['stablecoin-infrastructure', 'digital-payments'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'concentration-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/CRCLon',
    evidence: [],
  },
  {
    id: 'ins_ondo_spy',
    symbol: 'SPYon',
    name: 'SPDR S&P 500 ETF Trust (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Broad US equity',
    issuerName: 'Ondo Finance',
    underlying: 'SPY',
    represents: 'Tokenized economic exposure to SPDR S&P 500 ETF Trust. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['broad-market', 'us-equity'],
    exposures: ['broad-us-equity'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/SPYon',
    evidence: [],
  },
  {
    id: 'ins_ondo_qqq',
    symbol: 'QQQon',
    name: 'Invesco QQQ Trust (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Nasdaq equity',
    issuerName: 'Ondo Finance',
    underlying: 'QQQ',
    represents: 'Tokenized economic exposure to Invesco QQQ Trust. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['technology', 'nasdaq', 'big-tech', 'ai'],
    exposures: ['nasdaq-equity', 'technology-adoption'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/QQQon',
    evidence: [],
  },
  {
    id: 'ins_ondo_smh',
    symbol: 'SMHon',
    name: 'VanEck Semiconductor ETF (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Semiconductor demand',
    issuerName: 'Ondo Finance',
    underlying: 'SMH',
    represents: 'Tokenized economic exposure to VanEck Semiconductor ETF. Not direct ownership of the underlying security.',
    region: 'global',
    countryExposure: [],
    currencyExposure: ['USD'],
    themes: ['semiconductors', 'ai', 'compute'],
    exposures: ['semiconductor-demand', 'chip-manufacturing'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/SMHon',
    evidence: [],
  },
  {
    id: 'ins_ondo_xlu',
    symbol: 'XLUon',
    name: 'Utilities Select Sector SPDR Fund (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Power generation',
    issuerName: 'Ondo Finance',
    underlying: 'XLU',
    represents: 'Tokenized economic exposure to Utilities Select Sector SPDR Fund. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['utilities', 'energy', 'electricity', 'infrastructure'],
    exposures: ['power-generation', 'electricity-demand'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/XLUon',
    evidence: [],
  },
  {
    id: 'ins_ondo_xle',
    symbol: 'XLEon',
    name: 'Energy Select Sector SPDR Fund (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Energy demand',
    issuerName: 'Ondo Finance',
    underlying: 'XLE',
    represents: 'Tokenized economic exposure to Energy Select Sector SPDR Fund. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['energy', 'commodities'],
    exposures: ['energy-demand', 'oil-and-gas'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/XLEon',
    evidence: [],
  },
  {
    id: 'ins_ondo_gld',
    symbol: 'GLDon',
    name: 'SPDR Gold Shares (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Gold price',
    issuerName: 'Ondo Finance',
    underlying: 'GLD',
    represents: 'Tokenized economic exposure to SPDR Gold Shares. Not direct ownership of the underlying security.',
    region: 'global',
    countryExposure: [],
    currencyExposure: ['USD'],
    themes: ['gold', 'commodities', 'monetary-instability'],
    exposures: ['gold-price', 'monetary-hedge'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/GLDon',
    evidence: [],
  },
  {
    id: 'ins_ondo_tlt',
    symbol: 'TLTon',
    name: 'iShares 20+ Year Treasury Bond ETF (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Long duration treasuries',
    issuerName: 'Ondo Finance',
    underlying: 'TLT',
    represents: 'Tokenized economic exposure to iShares 20+ Year Treasury Bond ETF. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['treasuries', 'fixed-income'],
    exposures: ['long-duration-treasuries', 'interest-rate-duration'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/TLTon',
    evidence: [],
  },
  {
    id: 'ins_ondo_sgov',
    symbol: 'SGOVon',
    name: 'iShares 0-3 Month Treasury Bond ETF (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Short duration treasuries',
    issuerName: 'Ondo Finance',
    underlying: 'SGOV',
    represents: 'Tokenized economic exposure to iShares 0-3 Month Treasury Bond ETF. Not direct ownership of the underlying security.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['treasuries', 'fixed-income', 'liquidity'],
    exposures: ['short-duration-treasuries', 'usd-liquidity'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'eligibility-restrictions', 'fund-risk'],
    sourceUrl: 'https://app.ondo.finance/assets/SGOVon',
    evidence: [],
  },
  {
    id: 'ins_sol',
    symbol: 'SOL',
    name: 'Solana',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'digital_asset',
    exposureLabel: 'Blockchain settlement',
    issuerName: null,
    underlying: null,
    represents: 'Native network asset. Network adoption does not guarantee token returns.',
    region: 'global',
    countryExposure: [],
    currencyExposure: [],
    themes: ['solana', 'blockchain', 'infrastructure', 'tokenization', 'rwa', 'payments'],
    exposures: ['blockchain-settlement', 'solana-ecosystem', 'tokenization-infrastructure'],
    riskTags: ['volatility', 'protocol-risk', 'regulatory-risk'],
    sourceUrl: 'https://solana.com/learn/introduction-to-solana-tokens',
    evidence: [],
  },
  {
    id: 'ins_usdc',
    symbol: 'USDC',
    name: 'USDC',
    mint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
    decimals: 6,
    kind: 'cash',
    status: 'approved',
    instrumentType: 'stablecoin',
    exposureLabel: 'USD liquidity',
    issuerName: 'Circle',
    underlying: null,
    represents: 'USD stablecoin; holding it does not grant equity ownership or participation in issuer revenue.',
    region: 'global',
    countryExposure: [],
    currencyExposure: ['USD'],
    themes: ['stablecoins', 'payments', 'liquidity', 'tokenization', 'rwa'],
    exposures: ['usd-liquidity', 'digital-payments', 'stablecoin-infrastructure'],
    riskTags: ['issuer-risk', 'depeg-risk', 'regulatory-risk'],
    sourceUrl: 'https://www.circle.com/multi-chain-usdc/solana',
    evidence: [{ label: 'Circle: USDC contract addresses', url: 'https://developers.circle.com/stablecoins/usdc-contract-addresses', reviewedAt: '2026-10-09' }],
    detail: {
      issuerNature: 'Stablecoin issuer that holds reserves in cash and short-term US government obligations.',
      economicRights: [
        'Redeemable 1:1 for US dollars through Circle, for verified Circle customers.',
        'No interest, yield or ownership in Circle.',
      ],
      limitations: [
        'Not a bank deposit and not covered by deposit insurance.',
        'Holders without a Circle account rely on markets to convert it, where the price can drift from 1 USD.',
      ],
      costs: ['Solana network fees on each transaction.', 'Swap fees and price impact when converting through Jupiter.'],
      howToTrade: 'Swapped on Solana through Jupiter, one operation at a time, signed in your wallet.',
      eligibilityNotes: ['Anyone can hold and transfer it on Solana; redeeming directly with Circle requires a verified account.'],
    },
  },
  {
    id: 'ins_pyusd',
    symbol: 'PYUSD',
    name: 'PayPal USD',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'stablecoin',
    exposureLabel: 'USD liquidity',
    issuerName: 'Paxos',
    underlying: null,
    represents: 'USD stablecoin issued by Paxos, branded PayPal. Not equity or a claim on payment growth.',
    region: 'global',
    countryExposure: [],
    currencyExposure: ['USD'],
    themes: ['stablecoins', 'payments', 'liquidity'],
    exposures: ['usd-liquidity', 'digital-payments', 'stablecoin-infrastructure'],
    riskTags: ['issuer-risk', 'depeg-risk', 'regulatory-risk'],
    sourceUrl: 'https://developer.paypal.com/community/blog/pyusd-solana-token-extensions/',
    evidence: [],
  },
  {
    id: 'ins_usdy',
    symbol: 'USDY',
    name: 'Ondo US Dollar Yield',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_fixed_income',
    exposureLabel: 'Short duration treasuries',
    issuerName: 'Ondo Finance',
    underlying: null,
    represents: 'Tokenized instrument with short-term US Treasury and bank-deposit exposure. Not Ondo equity or direct participation in tokenization platform revenue.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['treasuries', 'fixed-income', 'tokenization', 'rwa'],
    exposures: ['short-duration-treasuries', 'tokenized-treasuries'],
    riskTags: ['issuer-risk', 'interest-rate-risk', 'eligibility-restrictions'],
    sourceUrl: 'https://ondo.finance/usdy',
    evidence: [],
  },
  {
    id: 'ins_ousg',
    symbol: 'OUSG',
    name: 'Ondo Short-Term US Government Treasuries',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_fixed_income',
    exposureLabel: 'Short duration treasuries',
    issuerName: 'Ondo Finance',
    underlying: null,
    represents: 'Tokenized fund exposure to short-term US government securities. Not equity in the tokenization provider.',
    region: 'us',
    countryExposure: ['US'],
    currencyExposure: ['USD'],
    themes: ['treasuries', 'fixed-income', 'tokenization', 'rwa'],
    exposures: ['short-duration-treasuries', 'tokenized-treasuries'],
    riskTags: ['fund-risk', 'issuer-risk', 'eligibility-restrictions'],
    sourceUrl: 'https://ondo.finance/ousg',
    evidence: [],
  },
  {
    id: 'ins_ondo_pbr',
    symbol: 'PBRon',
    name: 'Petrobras (Ondo tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_equity',
    exposureLabel: 'Brazil equities',
    issuerName: 'Ondo Finance',
    underlying: 'PBR',
    represents: 'Tokenized economic exposure to Petróleo Brasileiro S.A. – Petrobras through the U.S.-listed PBR instrument. It provides economic exposure to the underlying security and does not grant direct ownership of Petrobras shares.',
    region: 'brazil',
    countryExposure: ['BR'],
    currencyExposure: ['BRL', 'USD'],
    themes: ['brazil', 'energy', 'oil-and-gas', 'commodities', 'emerging-markets'],
    exposures: ['brazil-equities', 'brazil-energy', 'oil-and-gas', 'commodity-exporters', 'emerging-market-equities'],
    riskTags: ['market-risk', 'issuer-risk', 'tracking-risk', 'country-risk', 'currency-risk', 'commodity-risk', 'concentration-risk', 'eligibility-restrictions'],
    sourceUrl: 'https://app.ondo.finance/assets/PBRon',
    evidence: [],
  },
  {
    id: 'ins_backpack_ewz',
    symbol: 'EWZ',
    name: 'iShares MSCI Brazil ETF (Backpack tokenized)',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_etf',
    exposureLabel: 'Brazil equities',
    issuerName: 'Backpack',
    underlying: 'EWZ',
    represents: 'Tokenized representation of the iShares MSCI Brazil ETF, providing broad exposure to large- and mid-cap Brazilian equities.',
    region: 'brazil',
    countryExposure: ['BR'],
    currencyExposure: ['BRL', 'USD'],
    themes: ['brazil', 'latam', 'emerging-markets', 'equities'],
    exposures: ['brazil-equities', 'brazil-large-mid-cap', 'emerging-market-equities'],
    riskTags: ['market-risk', 'country-risk', 'currency-risk', 'issuer-risk', 'tracking-risk', 'concentration-risk'],
    sourceUrl: 'https://learn.backpack.exchange/blog/tokenized-ishares-msci-brazil-etf-ewz',
    evidence: [],
  },
  {
    id: 'ins_etherfuse_tesouro',
    symbol: 'TESOURO',
    name: 'Etherfuse Brazilian Treasury Bonds',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_fixed_income',
    exposureLabel: 'Brazil sovereign debt',
    issuerName: 'Etherfuse',
    underlying: null,
    represents: 'Tokenized exposure to Brazilian federal treasury bonds through Etherfuse Stablebonds, denominated in Brazilian reais.',
    region: 'brazil',
    countryExposure: ['BR'],
    currencyExposure: ['BRL'],
    themes: ['brazil', 'treasuries', 'fixed-income', 'sovereign-debt', 'rwa', 'tokenization'],
    exposures: ['brazil-sovereign-debt', 'brazil-interest-rates', 'brazil-local-fixed-income', 'brl-fixed-income', 'tokenized-treasuries'],
    riskTags: ['sovereign-risk', 'interest-rate-risk', 'currency-risk', 'issuer-risk', 'liquidity-risk', 'regulatory-risk'],
    sourceUrl: 'https://etherfuse.com/markets/brazil',
    evidence: [],
  },
  {
    id: 'ins_transfero_brz',
    symbol: 'BRZ',
    name: 'BRZ',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'stablecoin',
    exposureLabel: 'BRL liquidity',
    issuerName: 'Transfero',
    underlying: null,
    represents: 'Brazilian-real stablecoin designed to maintain a 1:1 reference to BRL. It represents BRL-denominated liquidity, not equity exposure to the Brazilian economy.',
    region: 'brazil',
    countryExposure: ['BR'],
    currencyExposure: ['BRL'],
    themes: ['brazil', 'stablecoins', 'payments', 'brl', 'liquidity', 'cross-border'],
    exposures: ['brl-liquidity', 'brazilian-real', 'digital-payments', 'cross-border-settlement'],
    riskTags: ['issuer-risk', 'depeg-risk', 'reserve-risk', 'regulatory-risk', 'currency-risk'],
    sourceUrl: 'https://transfero.com/brz-stablecoin',
    evidence: [],
  },
  {
    id: 'ins_etherfuse_cetes',
    symbol: 'CETES',
    name: 'Etherfuse Mexican Treasury Certificates',
    mint: null,
    decimals: null,
    kind: 'token',
    status: 'unavailable',
    instrumentType: 'tokenized_fixed_income',
    exposureLabel: 'Mexico sovereign debt',
    issuerName: 'Etherfuse',
    underlying: null,
    represents: 'Tokenized exposure to Mexican federal treasury certificates through Etherfuse Stablebonds, denominated in Mexican pesos.',
    region: 'latam',
    countryExposure: ['MX'],
    currencyExposure: ['MXN'],
    themes: ['mexico', 'latam', 'treasuries', 'fixed-income', 'sovereign-debt', 'rwa', 'tokenization'],
    exposures: ['mexico-sovereign-debt', 'mexico-interest-rates', 'mexico-local-fixed-income', 'mxn-fixed-income', 'tokenized-treasuries'],
    riskTags: ['sovereign-risk', 'interest-rate-risk', 'currency-risk', 'issuer-risk', 'liquidity-risk', 'regulatory-risk'],
    sourceUrl: 'https://etherfuse.com/markets/mexico',
    evidence: [],
  },
];
