export type ThesisLanguage = "pt" | "en";

// Localize deterministic catalog messages without another model request.
// Only the original belief is considered, never generated text or catalog labels.
export function thesisLanguage(belief: string): ThesisLanguage {
  const words =
    belief
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .match(/[a-z]+/g) ?? [];
  const portuguese = new Set([
    "acredito",
    "subir",
    "sobe",
    "cair",
    "caira",
    "cai",
    "taxa",
    "menor",
    "maior",
    "forte",
    "fraco",
    "perdera",
    "perder",
    "ganhar",
    "se",
    "vencer",
    "eletrica",
    "empresas",
    "acho",
    "quero",
    "tese",
    "vai",
    "vao",
    "sera",
    "serao",
    "crescer",
    "crescimento",
    "alta",
    "queda",
    "juros",
    "eleicao",
    "eleicoes",
    "vitoria",
    "dolar",
    "desvalorizacao",
    "valorizacao",
    "protecao",
    "economia",
    "brasileira",
    "brasileiro",
    "acoes",
    "renda",
    "demanda",
    "energia",
    "futuro",
    "porque",
    "que",
    "uma",
    "dos",
    "das",
    "com",
    "para",
    "nao",
    "apos",
  ]);
  const english = new Set([
    "i",
    "believe",
    "think",
    "want",
    "will",
    "would",
    "growth",
    "grow",
    "rise",
    "fall",
    "rates",
    "election",
    "elections",
    "dollar",
    "depreciation",
    "appreciation",
    "hedge",
    "economy",
    "brazilian",
    "stocks",
    "bonds",
    "demand",
    "energy",
    "future",
    "because",
    "the",
    "that",
    "with",
    "for",
    "after",
    "against",
  ]);
  const score = words.reduce(
    (n, word) => n + Number(portuguese.has(word)) - Number(english.has(word)),
    0,
  );
  return score > 0 ? "pt" : "en";
}
